### ISSUE TITLE
Documentation site 404

### ISSUE THREAD

**Issue by worikgh** [musitdev/portmidi-rs#38]
The documentation link on [crates.io](https://crates.io/crates/portmidi) is 404

http://musitdev.github.io/portmidi-rs/portmidi/index.html

**Comment by musitdev** [comment]
Thank you for the info. I look to see why the doc hasn't been generated correctly.

**Comment by musitdev** [comment]
I update the Cargo.toml to set the right documentation flag and publish the new version 0.2.6.
The documentation is now available from crates.io.
